# SGLang混合精度配置文件
# 用于配置不同精度权重的加载路径和映射关系

mixed_precision:
  # FP16权重文件路径 (原始模型路径)
  fp16_path: "/dcar-vepfs-trans-models/Qwen3-30B-A3B"
  
  # FP8权重文件路径
  fp8_path: "/dcar-vepfs-trans-models/Qwen3-30B-A3B-FP8"
  
  # Int4权重文件路径
  int4_path: "/dcar-vepfs-trans-models/Qwen3-30B-A3B-GPTQ-Int4"
  
  # 权重映射配置 - 指定哪些层使用哪种精度
  weight_mapping:
    
    # 专家层使用Int4
    "model.layers.0.mlp.experts.0.gate_proj.weight": "int4"
    "model.layers.0.mlp.experts.0.up_proj.weight": "int4"
    "model.layers.0.mlp.experts.0.down_proj.weight": "int4"
    "model.layers.0.mlp.experts.1.gate_proj.weight": "int4"
    "model.layers.0.mlp.experts.1.up_proj.weight": "int4"
    "model.layers.0.mlp.experts.1.down_proj.weight": "int4"

# 推理配置
inference:
  max_seq_length: 4096
  max_batch_size: 32
  dtype: "bfloat16"
  device_map: "auto"
  load_in_8bit: false
  load_in_4bit: false
